# sets up common build tools for the windows build machines before build

parameters:
  buildConfig: 'RelWithDebInfo'
  artifactName: 'onnxruntime-java-win-x64'
  version: ''
  comitId: ''
steps:
    - task: CmdLine@2
      inputs:
        script: |
          set NATIVE_FOLDER=$(Build.BinariesDirectory)\${{parameters.artifactName}}\stage\ai\onnxruntime\native\win-x64
          mkdir %NATIVE_FOLDER%
          mkdir $(Build.BinariesDirectory)\${{parameters.artifactName}}\lib
          echo "Directories created"
          copy .\java\build\libs\*.jar $(Build.BinariesDirectory)\${{parameters.artifactName}}\lib
          pushd $(Build.BinariesDirectory)\${{parameters.artifactName}}\lib
          jar xf onnxruntime-${{parameters.version}}.jar META-INF\maven\ai.onnxruntime\onnxruntime\pom.xml
          move META-INF\maven\ai.onnxruntime\onnxruntime\pom.xml onnxruntime-${{parameters.version}}.pom
          rd /s /q META-INF
          popd
          copy .\${{parameters.buildConfig}}\onnxruntime.pdb %NATIVE_FOLDER%
          copy .\${{parameters.buildConfig}}\onnxruntime4j_jni.pdb %NATIVE_FOLDER%
          copy $(Build.SourcesDirectory)\docs\Privacy.md $(Build.BinariesDirectory)\${{parameters.artifactName}}\stage\Privacy.md
          copy $(Build.SourcesDirectory)\ThirdPartyNotices.txt $(Build.BinariesDirectory)\${{parameters.artifactName}}\stage\ThirdPartyNotices.txt
          @echo ${{parameters.commitId}} > $(Build.BinariesDirectory)\${{parameters.artifactName}}\stage\GIT_COMMIT_ID
          dir /s /b .
          pushd $(Build.BinariesDirectory)\${{parameters.artifactName}}\stage
          jar uf $(Build.BinariesDirectory)\${{parameters.artifactName}}\lib\onnxruntime-${{parameters.version}}.jar ai\onnxruntime\native\win-x64\onnxruntime.pdb
          jar uf $(Build.BinariesDirectory)\${{parameters.artifactName}}\lib\onnxruntime-${{parameters.version}}.jar ai\onnxruntime\native\win-x64\onnxruntime4j_jni.pdb
          jar uf $(Build.BinariesDirectory)\${{parameters.artifactName}}\lib\onnxruntime-${{parameters.version}}.jar Privacy.md ThirdPartyNotices.txt GIT_COMMIT_ID
          popd
        workingDirectory: '$(Build.BinariesDirectory)\${{parameters.buildConfig}}'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)\${{parameters.artifactName}}\lib' 
        includeRootFolder: true
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        archiveFile: '$(Build.ArtifactStagingDirectory)\${{parameters.artifactName}}.zip'
        replaceExistingArchive: true 
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)\${{parameters.artifactName}}.zip' 
        artifactName: 'drop-${{parameters.artifactName}}'
