trigger: none

pool: Linux-GPU-CUDA10

steps:
    - checkout: self
      clean: true

    - task: CmdLine@2
      inputs:
        script: |
          df
          df /var/lib/docker
          docker info
          docker image ls
          docker container ls

    - task: CmdLine@2
      inputs:
        script: |
          docker image prune
          docker image rm $(docker image ls --format='{{.ID}}' onnxruntime-training-manylinux*)